config/routes.rb
Rails.application.routes.draw do
  get 'zo_ti/show'
  get 'zo_ti/home'
  get 'more/home'
  get 'more/news'
  get 'developers/user'
  get 'developers/home'
  get 'products/clock'
  get 'u/products'
  get 'u/user'
  get 'u/about'
  get 'error/400'
  get 'error/401'
  get 'error/403'
  get 'error/404'
  get 'error/503'
  root 'home#index'
  get '/zo_ti', to: 'zo_ti#show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  devise_for :users 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:user, :developer, :admin]
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  layout "developers_application"
end

app/controllers/error_controller.rb
class ErrorController < ApplicationController
  layout "error_application"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/more_controller.rb
class MoreController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def clock
  end
end

app/controllers/u_controller.rb
class UController < ApplicationController
  def index
  end
end

app/controllers/zo_ti_controller.rb
class ZoTiController < ApplicationController
  def home
  end
  require 'net/http'
  require 'json'

  def show
    @prompt = params[:prompt]

    uri = URI("https://afraid-glasses-drum-34-142-235-206.loca.lt/text2img/")
    params = { :prompt => @prompt }
    uri.query = URI.encode_www_form(params)

    response = Net::HTTP.get_response(uri)

    begin
      @image = JSON.parse(response.body)["image"]
    rescue JSON::ParserError => error
      return render json: { error: error.message }, status: :bad_request
    end

    respond_to do |format|
      format.html
      format.json { render json: @image }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/generate_images_helper.rb
module GenerateImagesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/more_helper.rb
module MoreHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/u_helper.rb
module UHelper
end

app/helpers/zo_ti_helper.rb
module ZoTiHelper
end

app/views/developers/home.html.erb
<% if current_user.role = 1 %>
    
    <div id="secpxhero" class="px-4 py-5 my-5 text-center">
                <img id="dmx4Logo" class="d-block mx-auto mb-4" src="<%= asset_path 'zd.svg' %>" alt="" width="150">
                <h1 id="titlehero1" class="display-5 fw-bold">Zode Developers</h1>
                <div class="col-lg-6 mx-auto">
                  <p id="herop" class="lead mb-4">A Big Platform That Let You To Do Cool Things</p>
                  <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                  <% if current_user %>
                    <%= link_to 'Try ZoTI', root_path, id:"btnhero1",class:"btn btn-outline-secondary btn-lg px-4" %>
                  <% else %>
                    <%= link_to 'Sign Up', new_user_registration_path, id:"btnhero1",class:"btn btn-outline-secondary btn-lg px-4" %>
                    <%= link_to 'Login', new_user_session_path, id:"btnhero2",class:"btn btn-outline-secondary btn-lg px-4" %>
                  <% end %>
                  </div>
                </div>
              </div>

    <div class="container col-xl-10 col-xxl-8 px-4 py-5">

    <div class="row align-items-center g-lg-5 py-5">
      <div class="col-lg-7 text-center text-lg-start">
        <h1 id="titlehero1" class="display-4 fw-bold lh-1 mb-3">You're a Developer ?</h1>
        <p id="herop" class="col-lg-10 fs-4">Join Zode Developers Community <br/> And Be a Zode Developer. <br/> Sign Up Right Now</p>
      </div>

      <div class="col-md-10 mx-auto col-lg-5">
        <form id="heroform" class="p-4 p-md-5 border rounded-3 bg-light">
          <div class="form-floating mb-3">
            <input required type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
            <label for="floatingInput">Email address</label>
          </div>
          <div class="form-floating mb-3">
            <textarea required class="form-control" id="floatingInputT" placeholder="Message"></textarea>
            <label for="floatingInput">You're Experince</label>
          </div>
          <button id="submit" class="w-100 btn btn-lg btn-primary" type="submit">Sign up</button>
          <hr class="my-4">
          <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small>
        </form>
      </div>
    </div>
  </div>


              <div class="container col-xxl-8 px-4 py-5">
                <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
                  <div class="col-10 col-sm-8 col-lg-6">
                    <img id="heroLogo" src="<%= asset_path 'Zode Word Logo.svg' %>" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="400" loading="lazy">
                  </div>
                  <div class="col-lg-6">
                    <h1 id="titlehero1" class="display-5 fw-bold lh-1 mb-3">Lorem, ipsum</h1>
                    <p id="herop" class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing.</p>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                        <a href=""><button id="btnhero1" type="button" class="btn btn-primary btn-lg px-4 me-md-2">Learn More</button></a>
                        <a href=""> <button id="btnhero2" type="button" class="btn btn-outline-secondary btn-lg px-4">Download SDK</button></a>
                    </div>
                  </div>
                </div>
              </div>
<% else %>
    <div class="container col-xxl-8 px-4 py-5">
                <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
                  <div class="col-10 col-sm-8 col-lg-6">
                    <img id="heroLogo" src="<%= asset_path 'Zode Word Logo.svg' %>" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="400" loading="lazy">
                  </div>
                  <div class="col-lg-6">
                    <h1 id="titlehero1" class="display-5 fw-bold lh-1 mb-3">Lorem, ipsum</h1>
                    <p id="herop" class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing.</p>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                        <a href=""><button id="btnhero1" type="button" class="btn btn-primary btn-lg px-4 me-md-2">Learn More</button></a>
                        <a href=""> <button id="btnhero2" type="button" class="btn btn-outline-secondary btn-lg px-4">Download SDK</button></a>
                    </div>
                  </div>
                </div>
              </div>
<% end %>

app/views/developers/user.html.erb
<% if current_user %>
    <div id="secpxhero" class="px-4 py-5 my-5 text-center">
                <h1 id="titlehero1" class="display-5 fw-bold">My Account</h1>
                <div class="col-lg-6 mx-auto">
                <p id="herop" class="lead mb-4">My Email: <em><%= current_user.email %></em></p>
                <p id="herop" class="lead mb-4">I'm: <em><%= current_user.role %></em></p>
                <p id="herop" class="lead mb-4">My ID: <em><%= current_user.id %></em></p>
                <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                    <%= link_to "SignOut!", destroy_user_session_path, 'data-turbo-method': :delete,  id:"btnhero2",class:"btn btn-outline-secondary btn-lg px-4" %>
                </div>
                </div>
            </div>
<% else %>
    <div id="secpxhero" class="px-4 py-5 my-5 text-center">
                <h1 id="titlehero1" class="display-5 fw-bold">Login</h1>
                <div class="col-lg-6 mx-auto">
                <p id="herop" class="lead mb-4">Or Sign Up</p>
                <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                    <%= link_to "Login!", new_user_session_path,  id:"btnhero2",class:"btn btn-outline-secondary btn-lg px-4" %>
                    <%= link_to "Sign Up!", new_user_registration_path,  id:"btnhero2",class:"btn btn-outline-secondary btn-lg px-4" %>
                </div>
                </div>
            </div>
<% end %>

app/views/home/_footer.html.erb
        <div class="container">
        
            <footer id="footd" class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
              <p class="col-md-4 mb-0 text-muted">&copy;<span id="Year"></span> Zode | All Rights Reserved</p>
              <%= link_to  root_path, class:"col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none" do %>
                <img id="footerLogo" width="65" src="<%= asset_path 'logos.svg' %>" alt="">
              <% end %>
              <ul class="nav col-md-4 justify-content-end">
                <li class="nav-item"><%= link_to 'Home', root_path, id:"btnme2",class:"nav-link px-2 text-muted" %></li>
                <li class="nav-item"><%= link_to 'Products', '/u/products', id:"btnme2",class:"nav-link px-2 text-muted" %></li>
                <li class="nav-item"><%= link_to 'More', '/more/home', id:"btnme2",class:"nav-link px-2 text-muted" %></li>
                <li class="nav-item"><%= link_to 'About', '/u/about', id:"btnme2",class:"nav-link px-2 text-muted" %></li>
              </ul>
            </footer>
          </div>  

app/views/home/_footer_developers.html.erb
        <div class="container">
        
            <footer id="footd" class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
              <p class="col-md-4 mb-0 text-muted">&copy;<span id="Year"></span> Zode | All Rights Reserved</p>
              <%= link_to  root_path, class:"col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none" do %>
                <img id="footerLogo" width="65" src="<%= asset_path 'zd.svg' %>" alt="">
              <% end %>
              <ul class="nav col-md-4 justify-content-end">
                <li class="nav-item"><%= link_to 'Home', root_path, id:"btnme2",class:"nav-link px-2 text-muted" %></li>
                <li class="nav-item"><%= link_to 'Products', '/u/products', id:"btnme2",class:"nav-link px-2 text-muted" %></li>
                <li class="nav-item"><%= link_to 'More', '/more/home', id:"btnme2",class:"nav-link px-2 text-muted" %></li>
                <li class="nav-item"><%= link_to 'About', '/u/about', id:"btnme2",class:"nav-link px-2 text-muted" %></li>
              </ul>
            </footer>
          </div>  

app/views/home/_header.html.erb
<header class="p-3-text-bg-dark">
            <div class="container">
              <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <%= link_to  root_path, class:"d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none" do%>
                 <img id="headerLogo" class="logo" src="<%= asset_path 'logos.svg' %>" alt="Zode Logo">
                <% end %>
        
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                  
                </ul>
                
                <%= link_to 'Home', root_path, id:"btnme2",class:"btn btn-outline-light me-2" %>
                <%= link_to 'Products', '/u/products', id:"btnme3",class:"btn btn-outline-light me-2" %>
                <%= link_to 'More', '/more/home', id:"btnme3",class:"btn btn-outline-light me-2" %>
                <%= link_to 'About', '/u/about', id:"btnme3",class:"btn btn-outline-light me-2" %>
              <% if current_user %>
                <%= link_to ' My Account', '/u/user', id:"btnme1",class:"bi bi-person-circle btn btn-outline-light me-2" %>
                <%= link_to 'Sign Out', destroy_user_session_path, 'data-turbo-method': :delete, id:"btnme1",class:"btn btn-outline-light me-2" %>
              <% else %>
                <%= link_to 'Sign Up', new_user_registration_path, id:"btnme1",class:"btn btn-outline-light me-2" %>
                <%= link_to 'Login', new_user_session_path, id:"btnme1",class:"btn btn-outline-light me-2" %>
              <% end %>
              </div>
            </div>
        </header>

app/views/home/_header_developers.html.erb
<header class="p-3-text-bg-dark">
            <div class="container">
              <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <%= link_to  root_path, class:"d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none" do%>
                 <img id="headerLogo" class="logo" src="<%= asset_path 'zd.svg' %>" alt="Zode Logo">
                <% end %>
        
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                  
                </ul>
                
                <%= link_to 'Home', root_path, id:"btnme2",class:"btn btn-outline-light me-2" %>
                <%= link_to 'Products', '/u/products', id:"btnme3",class:"btn btn-outline-light me-2" %>
                <%= link_to 'More', '/more/home', id:"btnme3",class:"btn btn-outline-light me-2" %>
                <%= link_to 'About', '/u/about', id:"btnme3",class:"btn btn-outline-light me-2" %>
              <% if current_user %>
                <%= link_to ' My Account', '/developers/user', id:"btnme1",class:"bi bi-person-circle btn btn-outline-light me-2" %>
                <%= link_to 'Sign Out', destroy_user_session_path, 'data-turbo-method': :delete, id:"btnme1",class:"btn btn-outline-light me-2" %>
              <% else %>
                <%= link_to 'Sign Up', new_user_registration_path, id:"btnme1",class:"btn btn-outline-light me-2" %>
                <%= link_to 'Login', new_user_session_path, id:"btnme1",class:"btn btn-outline-light me-2" %>
              <% end %>
              </div>
            </div>
        </header>

app/views/home/index.html.erb
    <div id="secpxhero" class="px-4 py-5 my-5 text-center">
                <h1 id="titlehero1" class="gradient" class="display-5 fw-bold">Some Gradient Text</h1>
                <img id="dmx4Logo" class="d-block mx-auto mb-4" src="<%= asset_path 'logos.svg' %>" alt="" width="150">
                <h1 id="titlehero1" class="display-5 fw-bold">Zode</h1>
                <div class="col-lg-6 mx-auto">
                  <p id="herop" class="lead mb-4">Lorem ipsum dolor sit</p>
                  <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                  <% if current_user %>
                    <%= link_to 'Try ZoTI', root_path, id:"btnhero1",class:"btn btn-outline-secondary btn-lg px-4" %>
                  <% else %>
                    <%= link_to 'Sign Up', new_user_registration_path, id:"btnhero1",class:"btn btn-outline-secondary btn-lg px-4" %>
                    <%= link_to 'Login', new_user_session_path, id:"btnhero2",class:"btn btn-outline-secondary btn-lg px-4" %>
                  <% end %>
                  </div>
                </div>
              </div>

    <div class="container col-xl-10 col-xxl-8 px-4 py-5">

    <div class="row align-items-center g-lg-5 py-5">
      <div class="col-lg-7 text-center text-lg-start">
        <h1 id="titlehero1" class="display-4 fw-bold lh-1 mb-3">You're a Developer ?</h1>
        <p id="herop" class="col-lg-10 fs-4">Join Zode Developers Comunity <br/> And Be a Zode Developer. <br/> Sign Up Right Now</p>
      </div>

      <div class="col-md-10 mx-auto col-lg-5">
        <form id="heroform" class="p-4 p-md-5 border rounded-3 bg-light">
          <div class="form-floating mb-3">
            <input required type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
            <label for="floatingInput">Email address</label>
          </div>
          <div class="form-floating mb-3">
            <textarea required class="form-control" id="floatingInputT" placeholder="Message"></textarea>
            <label for="floatingInput">You're Experince</label>
          </div>
          <button id="submit" class="w-100 btn btn-lg btn-primary" type="submit">Sign up</button>
          <hr class="my-4">
          <small class="text-muted">By clicking Sign up, you agree to the terms of use.</small>
        </form>
      </div>
    </div>
  </div>


              <div class="container col-xxl-8 px-4 py-5">
                <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
                  <div class="col-10 col-sm-8 col-lg-6">
                    <img id="heroLogo" src="<%= asset_path 'Zode Word Logo.svg' %>" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="400" loading="lazy">
                  </div>
                  <div class="col-lg-6">
                    <h1 id="titlehero1" class="display-5 fw-bold lh-1 mb-3">Lorem, ipsum</h1>
                    <p id="herop" class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing.</p>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                        <a href=""><button id="btnhero1" type="button" class="btn btn-primary btn-lg px-4 me-md-2">Learn More</button></a>
                        <a href=""> <button id="btnhero2" type="button" class="btn btn-outline-secondary btn-lg px-4">Download SDK</button></a>
                    </div>
                  </div>
                </div>
              </div>

app/views/layouts/application.html.erb
<!--  * -------------------------------------------------- *
      * © Copyright 2023 - Zode                            *
      * -------------------------------------------------- *
                                                              -->

<!DOCTYPE html>
<html>
  <head>
    <title>Zode</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="shortcut icon" type="image/png" href="<%= asset_path 'favicon.png' %>">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
  </head>

  <body>
</div>
    <%= render 'home/header' %>
    <section></section>
    <%= yield %>
    <%= render 'home/footer' %>
  </body>
</html>

app/views/layouts/developers_application.html.erb
<!--  * -------------------------------------------------- *
      * © Copyright 2023 - Zode                            *
      * -------------------------------------------------- *
                                                              -->
                                                              
<!DOCTYPE html>
<html>
  <head>
    <title>Zode | Developers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="shortcut icon" type="image/png" href="<%= asset_path 'zd.svg' %>">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
  </head>

  <body>
</div>
    <%= render 'home/header_developers' %>
    <section></section>
    <%= yield %>
    <%= render 'home/footer_developers' %>
  </body>
</html>

app/views/layouts/error_application.html.erb
<!--  * -------------------------------------------------- *
      * © Copyright 2023 - Zode                            *
      * -------------------------------------------------- *
                                                              -->

<!DOCTYPE html>
<html>
  <head>
    <title>Zode | Error</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="shortcut icon" type="image/png" href="<%= asset_path 'favicon.png' %>">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags  %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
  </head>

  <body>
</div>
    <style>
      * {
        color: #ffff;
      }
      .mt-5 {
        color: #00fe81;
        font-weight: bold;
        font-size: 4rem;
      }
      .mt-4 {
        color: #00ffdd;
        font-weight: bold;
        font-size: 2rem;
      }
      .container {
        margin-top: 0px;
      }
      #Year {
        color:;
      }
    </style>
    <%= yield %>
            <div class="container">
            <footer id="footd" class="d-flex flex-wrap justify-content-center align-items-center py-3 my-4 border-top">
              <p class="col-md-4 mb-0 text-muted">&copy;<span class="col-md-4 mb-0 text-muted" id="Year"></span> Zode | All Rights Reserved</p>
            </footer>
          </div>  
  </body>
</html>

app/views/products/clock.html.erb
    <div id="secpxhero" class="px-4 py-5 my-5 text-center">
                <img id="dmx4Logo" class="d-block mx-auto mb-4" src="<%= asset_path 'zos.svg' %>" alt="" width="100">
                <h1 id="titlehero1" class="gradient fw-bold"><i class="bi bi-stopwatch"></i> <br /> Stop Watch</h1>
                <div id="titlehero1" class="timerDisplay fw-bold">
                    00 : 00 : 00 : 000
                </div>
                <div class="buttons">
                    <button id="pauseTimer">Pause</button>
                    <button id="startTimer">Start</button>
                    <button id="resetTimer">Reset</button>
                </div>
                <br />
                <br />
                <h1 id="titlehero1" class="gradient fw-bold"><i class="bi bi-clock"></i> <br />Your Local Time</h1>
                <h1 id="titlehero1" class="display-5 fw-bold"><span id="date"></span></h1>
                <h1 id="titlehero1" class="display-5 fw-bold"><span id="clock"></span></h1>
    </div>

app/views/zo_ti/home.html.erb
    <div id="secpxhero" class="px-4 py-5 my-5 text-center">
                <h1 id="titlehero1" class="gradient" class="display-5 fw-bold">Some Gradient Text</h1>
                <img id="dmx4Logo" class="d-block mx-auto mb-4" src="<%= asset_path 'zos.svg' %>" alt="" width="150">
                <h1 id="titlehero1" class="display-5 fw-bold">ZoTI</h1>
                <div class="col-lg-6 mx-auto">
                  <p id="herop" class="lead mb-4">Lorem ipsum dolor sit</p>
                  <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                  <% if current_user %>
                    <%= link_to 'Try ZoTI', root_path, id:"btnhero1",class:"btn btn-outline-secondary btn-lg px-4" %>
                  <% else %>
                    <%= link_to 'Sign Up', new_user_registration_path, id:"btnhero1",class:"btn btn-outline-secondary btn-lg px-4" %>
                    <%= link_to 'Login', new_user_session_path, id:"btnhero2",class:"btn btn-outline-secondary btn-lg px-4" %>
                  <% end %>
                  </div>
                </div>
              </div>

    <div class="container col-xl-10 col-xxl-8 px-4 py-5">

<% if current_user %>

            
        <div class="col-md-10 mx-auto col-lg-5">
            <%= form_tag zo_ti_path, id:"heroform", class:"p-4 p-md-5 border rounded-3 bg-light" , method: :get do  %>
                <div class="form-floating mb-3">
                <%= text_field_tag :prompt, params[:prompt], id:'floatingInput', class:"form-control" %>
                <br />
                <%= submit_tag "Generate", id:"submit", class:"w-100 btn btn-lg btn-primary" %>
                </div>
            <% end %>

            <% if @image.present? %>
                <%= image_tag @image %>
            <% end %>
        </div>
<% else %>



<% end %>


              <div class="container col-xxl-8 px-4 py-5">
                <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
                  <div class="col-10 col-sm-8 col-lg-6">
                    <img id="heroLogo" src="<%= asset_path 'Zode Word Logo.svg' %>" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="400" loading="lazy">
                  </div>
                  <div class="col-lg-6">
                    <h1 id="titlehero1" class="display-5 fw-bold lh-1 mb-3">Lorem, ipsum</h1>
                    <p id="herop" class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing.</p>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                        <a href=""><button id="btnhero1" type="button" class="btn btn-primary btn-lg px-4 me-md-2">Learn More</button></a>
                        <a href=""> <button id="btnhero2" type="button" class="btn btn-outline-secondary btn-lg px-4">Download SDK</button></a>
                    </div>
                  </div>
                </div>
              </div>

app/views/zo_ti/show.html.erb
<% if @image.present? %>
        <%= image_tag @image %>
<% end %>